### ISSUE TITLE
Customize Chromium so it consumes less data

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6bin#25] opened 2015-12-07 13:15 UTC
https://www.chromium.org/developers/how-tos/run-chromium-with-flags
http://peter.sh/experiments/chromium-command-line-switches/

Consider the following flags:
- `--safebrowsing-disable-auto-update` "If present, safebrowsing only performs update when SafeBrowsingProtocolManager::ForceScheduleNextUpdate() is explicitly called. This is used for testing only."
- `--bwsi` "Indicates that the browser is in "browse without sign-in" (Guest session) mode. Should completely disable extensions, sync and bookmarks."
- `--disable-background-networking` "Disable several subsystems which run network requests in the background. This is for use when doing network performance testing to avoid noise in the measurements."
- `--disable-extensions` "Disable extensions"
- `--disable-sync` "Disables syncing browser data to a Google Account."
- `--no-experiments` "Disables all experiments set on about:flags. Does not disable about:flags itself. Useful if an experiment makes chrome crash at startup: One can start chrome with --no-experiments, disable the problematic lab at about:flags and then restart chrome without this switch again."
- `--no-first-run` "Skip First Run tasks, whether or not it's actually the First Run. Overridden by kForceFirstRun. This does not drop the First Run sentinel and thus doesn't prevent first run from occuring the next time chrome is launched without this flag."
- `--no-pings` "Don't send hyperlink auditing pings"
- `--kiosk`

Interesting, but not sure:
- `--disable-quic` "Disables support for the QUIC protocol."
- `--disable-infobars` "Prevent infobars from appearing."

**Comment by vallettea** [comment] 2015-12-07 14:34
We can have a look at [apparmor](http://wiki.apparmor.net/index.php/Main_Page)

these guys did exactly what we want:
http://ubuntuforums.org/showthread.php?t=1837437
http://unix.stackexchange.com/questions/135115/apparmor-profile-deny-internet-access
http://askubuntu.com/questions/679474/how-to-block-internet-access-for-an-application

the problem is that i think we need to recompile the kernel
https://wiki.debian.org/AppArmor/HowToUse
http://wiki.apparmor.net/index.php/Distro_debian

but there is no grub on jessie so maybe like this
http://elinux.org/Raspberry_Pi_Kernel_Compilation

**Comment by DavidBruant** [comment] 2015-12-07 14:57
Starting Chromium with [unshare -n](http://linux.die.net/man/1/unshare) looked like a [promising option](http://unix.stackexchange.com/a/83348). However, unshare creates a completely new Linux networking [namespace](https://lwn.net/Articles/531114/) which cannot share one of the actual network interface. Two processes using two network namespaces cannot discuss locally via the network.
It's however possible for two processes to share the same (new) namespace via `nsenter`, but in our case it would have been going back to square one.

**Comment by bleucitron** [comment] 2015-12-09 13:38
Closed by configuring the sensors

**Closed as completed by bleucitron** 2015-12-09 13:38 UTC
